before_script:
  - docker version
  - docker compose version
  - pwd
  - ls -la

stages:
  - setup-ci
  - check-lint-format
  #- test
  - build-prod
  - deploy-prod
  - build-acc
  - deploy-acc

setup-ci:
  stage: setup-ci
  script:
    - docker compose -p api-catalogue-backend-ci -f docker-compose.ci.yml up --build -d
  only:
    - master
    - main
  tags:
    - api-catalogue-prod

check-lint-format:
  stage: check-lint-format
  script:
    - docker compose -p api-catalogue-backend-ci -f docker-compose.ci.yml run ec_api_catalogue_backend npm run check-lint-and-format-repo
  only:
    - master
    - main
  tags:
    - api-catalogue-prod

test:
  stage: test
  script:
    - docker compose -p api-catalogue-backend-ci -f docker-compose.ci.yml up -d mongodb
    - docker compose -p api-catalogue-backend-ci -f docker-compose.ci.yml run ec_api_catalogue_backend npm run test
  after_script:
    - docker compose -p api-catalogue-backend-ci -f docker-compose.ci.yml down
    - docker image prune -f
  only:
    - master
    - main
  tags:
    - api-catalogue-prod

build-prod:
  stage: build-prod
  script:
    - ls -latr
    - docker build --target prod -t api-catalogue-backend:latest .
  only:
    - master
    - main
  tags:
    - api-catalogue-prod

deploy-prod:
  stage: deploy-prod
  script:
    - docker compose -f /home/gitlab-runner/api-catalogue-backend/docker-compose.prod.yml down
    - cp docker-compose.prod.yml /home/gitlab-runner/api-catalogue-backend/
    - docker compose -f /home/gitlab-runner/api-catalogue-backend/docker-compose.prod.yml up -d
  only:
    - master
    - main
  tags:
    - api-catalogue-prod

build-acc:
  stage: build-acc
  script:
    - ls -latr
    - docker build --target prod -t api-catalogue-backend:latest .
  only:
    - dev
  tags:
    - api-catalogue-acc

deploy-acc:
  stage: deploy-acc
  script:
    - rm -rf /home/pauldb/eur/api-catalogue-backend
    - ln -s "$(pwd)" /home/pauldb/eur/api-catalogue-backend
    - cd /home/pauldb/eur/api-catalogue-backend
    - docker compose -f /home/pauldb/eur/api-catalogue-backend/docker-compose.acc.yml down
    - docker compose -f /home/pauldb/eur/api-catalogue-backend/docker-compose.acc.yml up -d
  only:
    - dev
  tags:
    - api-catalogue-acc
