services:
  ec_api_catalogue_backend:
    image: api-catalogue-backend:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER_NAME}:${MONGODB_USER_PASSWORD}@mongodb/ec_api_catalogue_backend
    env_file:
      - .env
    ports:
      - '5510:3000'

  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_USER_NAME=${MONGODB_USER_NAME}
      - MONGO_INITDB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
      - NODE_ENV=production
    volumes:
      - mongodb_data:/data/db
      - ./src/utils/dev-mongo-init/:/docker-entrypoint-initdb.d/:ro

volumes:
  mongodb_data:
