version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - '--log.level=INFO'
      - '--api.insecure=false'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.letsencrypt.acme.tlschallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.email=thomas.ritaine@ext.ec.europa.eu'
      - '--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'letsencrypt:/letsencrypt'

  ec_api_catalogue_backend:
    image: api-catalogue-backend:latest
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER_NAME}:${MONGODB_USER_PASSWORD}@mongodb/ec_api_catalogue_backend
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ec-api-catalogue.rule=Host(`${DOMAIN_NAME}`)'
      - 'traefik.http.routers.ec-api-catalogue.entrypoints=websecure'
      - 'traefik.http.routers.ec-api-catalogue.tls.certresolver=letsencrypt'

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_USER_NAME=${MONGODB_USER_NAME}
      - MONGO_INITDB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
      - NODE_ENV=production
    volumes:
      - mongodb_data:/data/db

volumes:
  letsencrypt:
  mongodb_data:
