version: '3.8'
services:
    ec_api_catalogue_backend:
        build: .
        ports:
            - '5010:8080'
            #- '9229:9229' # nodejs debugging port
        #command: node --inspect=0.0.0.0 dist/index.js
        restart: unless-stopped
