version: '3.8'
services:
    backend:
        build: .
        ports:
            - '5010:5010'
            - '9229:9229' # nodejs debugging port
        command: node --inspect=0.0.0.0 dist/index.js
        environment:
            NODE_ENV: development
            BIND_IP: 0.0.0.0
            BIND_PORT: 5010
