services:
  ec_api_catalogue_backend:
    image: node:20
    depends_on:
      - mongodb
    working_dir: /usr/src/app
    user: node:node
    environment:
      - NODE_ENV=development
      - ACCESS_LOG_PATH=logs/access.log
      - AUTH_JWT_SECRET=super-secret-never-share
      - SENTRY_DSN=""
      - MONGODB_URI=mongodb://webapp:password@mongodb/ec_api_catalogue_backend
      - MONGODB_TEST_URI=mongodb://test:testpassword@mongodb/ec_api_catalogue_backend_test
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: npm run dev

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_USER_NAME=webapp
      - MONGO_INITDB_USER_PASSWORD=password
      - MONGO_INITDB_TEST_NAME=test
      - MONGO_INITDB_TEST_PASSWORD=testpassword
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
      - NODE_ENV=development
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./src/utils/dev-mongo-init/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - '8081:8081'

volumes:
  mongodb_data:
