services:
  ec_api_catalogue_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - ACCESS_LOG_PATH=logs/access.log
      - AUTH_JWT_SECRET=super-secret-never-share
      - SENTRY_DSN=""
      - MONGODB_URI=mongodb://webapp:password@mongodb/ec_api_catalogue_backend
      - MONGODB_TEST_URI=mongodb://test:testpassword@mongodb/ec_api_catalogue_backend_test

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_USER_NAME=webapp
      - MONGO_INITDB_USER_PASSWORD=password
      - MONGO_INITDB_TEST_NAME=test
      - MONGO_INITDB_TEST_PASSWORD=testpassword
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
    volumes:
      - ./src/utils/dev-mongo-init/:/docker-entrypoint-initdb.d/:ro
