version: "3.8"

services:
  ec_api_catalogue_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER_NAME}:${MONGODB_USER_PASSWORD}@mongodb/ec_api_catalogue_backend
    env_file:
      - .env
    volumes:
      - backend_data:/data
      - /home/pauldb/eur/data/logs:/data/logs
    # ports:
    #   - '3000:3000'
    labels:
      - "traefik.enable=true"
      # - 'traefik.http.routers.ec_api_catalogue_backend.rule=Host(`api.localhost`)'
      - "traefik.http.routers.ec_api_catalogue_backend.rule=Host(`mercurius.debuck.tech`)"
      - "traefik.http.routers.ec_api_catalogue_backend.entrypoints=websecure"
      - "traefik.http.routers.ec_api_catalogue_backend.tls=true"
      # - 'traefik.http.routers.ec_api_catalogue_backend.tls.certresolver=letsencrypt'
      - "traefik.http.routers.ec_api_catalogue_backend.tls.certresolver=localhostresolver"
      - "traefik.http.services.ec_api_catalogue_backend.loadbalancer.server.port=3000"

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_USER_NAME=${MONGODB_USER_NAME}
      - MONGO_INITDB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
    volumes:
      - mongodb_data:/data/db
      - ./src/utils/dev-mongo-init/:/docker-entrypoint-initdb.d/:ro

  # Traefik Reverse Proxy
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:5010"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=thomas.ritaine@ext.ec.europa.eu"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.localhostresolver.tls=true"
    ports:
      - "5010:5010"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    depends_on:
      - ec_api_catalogue_backend
  # labels:
  #   - 'traefik.enable=true'
  #   - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
  #   - 'traefik.http.routers.api.entrypoints=websecure'
  #   - 'traefik.http.routers.api.tls=true'
  #   - 'traefik.http.routers.api.tls.certresolver=localhostresolver'
  #   - 'traefik.http.services.api.loadbalancer.server.port=3000'

volumes:
  backend_data:
  mongodb_data:
  letsencrypt:
