version: '3.8'

services:
  ec_api_catalogue_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER_NAME}:${MONGODB_USER_PASSWORD}@mongodb/ec_api_catalogue_backend
    env_file:
      - .env
    volumes:
      - /home/pauldb/eur/data:/data
      - /home/pauldb/eur/data/logs:/data/logs
    ports:
      - '5510:3000'

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_USER_NAME=${MONGODB_USER_NAME}
      - MONGO_INITDB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - MONGO_INITDB_DATABASE=ec_api_catalogue_backend
    volumes:
      - mongodb_data:/data/db
      - ./src/utils/dev-mongo-init/:/docker-entrypoint-initdb.d/:ro

volumes:
  mongodb_data:
